name: Build MacOS Application Python 2.7

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 2.7
      uses: actions/setup-python@v3
      with:
        python-version: "2.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-build-py27.txt
    - name: Build
      run: |
        rm -rf build
        rm -rf dist
        python -c "import platform;print(platform.mac_ver())"
        python -c "import sys;print(sys.version)"
        python setup.py py2app
    - name: Create Zip Package
      run: |
        zip -r ./dist/TrojanA-app-macos-10.14.zip ./dist/TrojanA.app
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TrojanA-app-macos-10.14
        path: ./dist/TrojanA-app-macos-10.14.zip
    - name: Upload Release File
      if: ${{ github.event_name == 'release'}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ github.event.release.tag_name }}
      run: |
        gh release upload "$TAG_NAME" ./dist/TrojanA-app-macos-10.14.zip